export const IMPORT_LIST_REQUEST = 'IMPORT_LIST_REQUEST'
export const IMPORT_LIST_SUCCESS = 'IMPORT_LIST_SUCCESS'
export const IMPORT_LIST_FAIL = 'IMPORT_LIST_FAIL'
export const IMPORT_LIST_RESET = 'IMPORT_LIST_RESET'

export const IMPORT_DETAILS_REQUEST = 'IMPORT_DETAILS_REQUEST'
export const IMPORT_DETAILS_SUCCESS = 'IMPORT_DETAILS_SUCCESS'
export const IMPORT_DETAILS_FAIL = 'IMPORT_DETAILS_FAIL'
export const IMPORT_DETAILS_RESET = 'IMPORT_DETAILS_RESET'

export const IMPORT_CREATE_REQUEST = 'IMPORT_CREATE_REQUEST'
export const IMPORT_CREATE_SUCCESS = 'IMPORT_CREATE_SUCCESS'
export const IMPORT_CREATE_FAIL = 'IMPORT_CREATE_FAIL'
export const IMPORT_CREATE_RESET = 'IMPORT_CREATE_RESET'

export const IMPORT_STATUS_REQUEST = 'IMPORT_STATUS_REQUEST'
export const IMPORT_STATUS_SUCCESS = 'IMPORT_STATUS_SUCCESS'
export const IMPORT_STATUS_FAIL = 'IMPORT_STATUS_FAIL'
export const IMPORT_STATUS_RESET = 'IMPORT_STATUS_RESET'
