export const ORDER_SUPPLIER_LIST_REQUEST = 'ORDER_SUPPLIER_LIST_REQUEST'
export const ORDER_SUPPLIER_LIST_SUCCESS = 'ORDER_SUPPLIER_LIST_SUCCESS'
export const ORDER_SUPPLIER_LIST_FAIL = 'ORDER_SUPPLIER_LIST_FAIL'
export const ORDER_SUPPLIER_LIST_RESET = 'ORDER_SUPPLIER_LIST_RESET'

export const ORDER_SUPPLIER_DETAILS_REQUEST = 'ORDER_SUPPLIER_DETAILS_REQUEST'
export const ORDER_SUPPLIER_DETAILS_SUCCESS = 'ORDER_SUPPLIER_DETAILS_SUCCESS'
export const ORDER_SUPPLIER_DETAILS_FAIL = 'ORDER_SUPPLIER_DETAILS_FAIL'
export const ORDER_SUPPLIER_DETAILS_RESET = 'ORDER_SUPPLIER_DETAILS_RESET'

export const ORDER_SUPPLIER_CREATE_REQUEST = 'ORDER_SUPPLIER_CREATE_REQUEST'
export const ORDER_SUPPLIER_CREATE_SUCCESS = 'ORDER_SUPPLIER_CREATE_SUCCESS'
export const ORDER_SUPPLIER_CREATE_FAIL = 'ORDER_SUPPLIER_CREATE_FAIL'
export const ORDER_SUPPLIER_CREATE_RESET = 'ORDER_SUPPLIER_CREATE_RESET'

export const ORDER_SUPPLIER_STATUS_REQUEST = 'ORDER_SUPPLIER_STATUS_REQUEST'
export const ORDER_SUPPLIER_STATUS_SUCCESS = 'ORDER_SUPPLIER_STATUS_SUCCESS'
export const ORDER_SUPPLIER_STATUS_FAIL = 'ORDER_SUPPLIER_STATUS_FAIL'
export const ORDER_SUPPLIER_STATUS_RESET = 'ORDER_SUPPLIER_STATUS_RESET'
