export const WISHLIST_MY = 'WISHLIST_MY'
export const WISHLIST_REMOVE_ALL_ITEM = 'WISHLIST_REMOVE_ALL_ITEM'
export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM'
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM'
